# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop_app/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainApp(object):
    def setupUi(self, TrainApp):
        TrainApp.setObjectName("TrainApp")
        TrainApp.resize(1200, 881)
        TrainApp.setAutoFillBackground(False)
        TrainApp.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(TrainApp)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setContentsMargins(5, -1, 5, -1)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.load_images_button = QtWidgets.QPushButton(self.verticalWidget)
        self.load_images_button.setEnabled(True)
        self.load_images_button.setMouseTracking(True)
        self.load_images_button.setDefault(True)
        self.load_images_button.setObjectName("load_images_button")
        self.verticalLayout_3.addWidget(self.load_images_button)
        self.load_model = QtWidgets.QPushButton(self.verticalWidget)
        self.load_model.setEnabled(True)
        self.load_model.setMinimumSize(QtCore.QSize(170, 0))
        self.load_model.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.load_model.setMouseTracking(True)
        self.load_model.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.load_model.setStyleSheet("")
        self.load_model.setDefault(True)
        self.load_model.setObjectName("load_model")
        self.verticalLayout_3.addWidget(self.load_model)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.box_bound_button = QtWidgets.QPushButton(self.verticalWidget)
        self.box_bound_button.setEnabled(True)
        self.box_bound_button.setMinimumSize(QtCore.QSize(170, 0))
        self.box_bound_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.box_bound_button.setMouseTracking(True)
        self.box_bound_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_bound_button.setDefault(True)
        self.box_bound_button.setObjectName("box_bound_button")
        self.verticalLayout_3.addWidget(self.box_bound_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.image_view = UAnnotableGraphicsView(self.centralwidget)
        self.image_view.setMinimumSize(QtCore.QSize(0, 480))
        self.image_view.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.image_view.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.image_view.setObjectName("image_view")
        self.horizontalLayout.addWidget(self.image_view)
        self.main_layout.addLayout(self.horizontalLayout)
        self.round_images = UHorizontalScrollArea(self.centralwidget)
        self.round_images.setMinimumSize(QtCore.QSize(0, 175))
        self.round_images.setMaximumSize(QtCore.QSize(16777215, 220))
        self.round_images.setMouseTracking(True)
        self.round_images.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.round_images.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.round_images.setWidgetResizable(True)
        self.round_images.setObjectName("round_images")
        self.scroll_content = QtWidgets.QWidget()
        self.scroll_content.setGeometry(QtCore.QRect(0, 0, 1166, 218))
        self.scroll_content.setMouseTracking(True)
        self.scroll_content.setObjectName("scroll_content")
        self.round_images.setWidget(self.scroll_content)
        self.main_layout.addWidget(self.round_images)
        self.toggle_round_images = QtWidgets.QPushButton(self.centralwidget)
        self.toggle_round_images.setEnabled(True)
        self.toggle_round_images.setMouseTracking(True)
        self.toggle_round_images.setAutoFillBackground(False)
        self.toggle_round_images.setStyleSheet("margin-top: 5px;")
        self.toggle_round_images.setAutoRepeat(False)
        self.toggle_round_images.setDefault(True)
        self.toggle_round_images.setObjectName("toggle_round_images")
        self.main_layout.addWidget(self.toggle_round_images)
        self.verticalLayout_2.addLayout(self.main_layout)
        TrainApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrainApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        TrainApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrainApp)
        self.statusbar.setObjectName("statusbar")
        TrainApp.setStatusBar(self.statusbar)

        self.retranslateUi(TrainApp)
        QtCore.QMetaObject.connectSlotsByName(TrainApp)

    def retranslateUi(self, TrainApp):
        _translate = QtCore.QCoreApplication.translate
        TrainApp.setWindowTitle(_translate("TrainApp", "Train App"))
        self.load_images_button.setText(_translate("TrainApp", "Загрузить картинки"))
        self.load_model.setText(_translate("TrainApp", "Загрузить .pt"))
        self.box_bound_button.setText(_translate("TrainApp", "Начать выделение"))
        self.toggle_round_images.setText(_translate("TrainApp", "Скрыть карусель"))
from annotable import UAnnotableGraphicsView
from custom_widgets import UHorizontalScrollArea


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainApp = QtWidgets.QMainWindow()
    ui = Ui_TrainApp()
    ui.setupUi(TrainApp)
    TrainApp.show()
    sys.exit(app.exec_())
