# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_class_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_add_class(object):
    def setupUi(self, dialog_add_class):
        dialog_add_class.setObjectName("dialog_add_class")
        dialog_add_class.resize(313, 144)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(dialog_add_class)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(dialog_add_class)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineedit_name_class = QtWidgets.QLineEdit(dialog_add_class)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineedit_name_class.setFont(font)
        self.lineedit_name_class.setObjectName("lineedit_name_class")
        self.verticalLayout_2.addWidget(self.lineedit_name_class)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_choose_color = QtWidgets.QPushButton(dialog_add_class)
        self.button_choose_color.setMinimumSize(QtCore.QSize(0, 25))
        self.button_choose_color.setObjectName("button_choose_color")
        self.horizontalLayout.addWidget(self.button_choose_color)
        self.label_color = QtWidgets.QLabel(dialog_add_class)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_color.setFont(font)
        self.label_color.setText("")
        self.label_color.setObjectName("label_color")
        self.horizontalLayout.addWidget(self.label_color)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.button_confirm = QtWidgets.QPushButton(dialog_add_class)
        self.button_confirm.setObjectName("button_confirm")
        self.verticalLayout_2.addWidget(self.button_confirm)

        self.retranslateUi(dialog_add_class)
        QtCore.QMetaObject.connectSlotsByName(dialog_add_class)

    def retranslateUi(self, dialog_add_class):
        _translate = QtCore.QCoreApplication.translate
        dialog_add_class.setWindowTitle(_translate("dialog_add_class", "Добавить класс"))
        self.label.setText(_translate("dialog_add_class", "Введите имя класса:"))
        self.button_choose_color.setText(_translate("dialog_add_class", "Выбрать цвет"))
        self.button_confirm.setText(_translate("dialog_add_class", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_add_class = QtWidgets.QDialog()
    ui = Ui_dialog_add_class()
    ui.setupUi(dialog_add_class)
    dialog_add_class.show()
    sys.exit(app.exec_())
