# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotation_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotataion_page(object):
    def setupUi(self, annotataion_page):
        annotataion_page.setObjectName("annotataion_page")
        annotataion_page.resize(1388, 885)
        annotataion_page.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.page_main_layout = QtWidgets.QVBoxLayout(annotataion_page)
        self.page_main_layout.setObjectName("page_main_layout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_to_datasets_settings = QtWidgets.QPushButton(annotataion_page)
        self.button_to_datasets_settings.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid #7a7b7d;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_datasets_settings.setObjectName("button_to_datasets_settings")
        self.horizontalLayout_7.addWidget(self.button_to_datasets_settings)
        self.button_to_annotation_scene = QtWidgets.QPushButton(annotataion_page)
        self.button_to_annotation_scene.setTabletTracking(False)
        self.button_to_annotation_scene.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_annotation_scene.setObjectName("button_to_annotation_scene")
        self.horizontalLayout_7.addWidget(self.button_to_annotation_scene)
        self.button_to_statistics = QtWidgets.QPushButton(annotataion_page)
        self.button_to_statistics.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_statistics.setObjectName("button_to_statistics")
        self.horizontalLayout_7.addWidget(self.button_to_statistics)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.button_clear_dataset = QtWidgets.QPushButton(annotataion_page)
        self.button_clear_dataset.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_clear_dataset.setObjectName("button_clear_dataset")
        self.horizontalLayout_7.addWidget(self.button_clear_dataset)
        self.page_main_layout.addLayout(self.horizontalLayout_7)
        self.display_layout = QtWidgets.QVBoxLayout()
        self.display_layout.setContentsMargins(0, -1, 0, -1)
        self.display_layout.setObjectName("display_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalWidget_3 = QtWidgets.QWidget(annotataion_page)
        self.verticalWidget_3.setMinimumSize(QtCore.QSize(250, 0))
        self.verticalWidget_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.load_images_button = QtWidgets.QPushButton(self.verticalWidget_3)
        self.load_images_button.setEnabled(True)
        self.load_images_button.setMouseTracking(True)
        self.load_images_button.setDefault(True)
        self.load_images_button.setObjectName("load_images_button")
        self.verticalLayout_6.addWidget(self.load_images_button)
        self.auto_annotate_checkbox = QtWidgets.QCheckBox(self.verticalWidget_3)
        self.auto_annotate_checkbox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.auto_annotate_checkbox.setFont(font)
        self.auto_annotate_checkbox.setObjectName("auto_annotate_checkbox")
        self.verticalLayout_6.addWidget(self.auto_annotate_checkbox)
        self.list_class_selector = UClassSelectorList(self.verticalWidget_3)
        self.list_class_selector.setMinimumSize(QtCore.QSize(0, 300))
        self.list_class_selector.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_class_selector.setObjectName("list_class_selector")
        self.verticalLayout_6.addWidget(self.list_class_selector)
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.select_dragmode_button = QtWidgets.QPushButton(self.verticalWidget_3)
        self.select_dragmode_button.setMinimumSize(QtCore.QSize(0, 0))
        self.select_dragmode_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_dragmode_button.setBaseSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_dragmode_button.setFont(font)
        self.select_dragmode_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.select_dragmode_button.setObjectName("select_dragmode_button")
        self.verticalLayout_6.addWidget(self.select_dragmode_button)
        self.select_annotatemode_button = QtWidgets.QPushButton(self.verticalWidget_3)
        self.select_annotatemode_button.setMinimumSize(QtCore.QSize(0, 0))
        self.select_annotatemode_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.select_annotatemode_button.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.select_annotatemode_button.setFont(font)
        self.select_annotatemode_button.setObjectName("select_annotatemode_button")
        self.verticalLayout_6.addWidget(self.select_annotatemode_button)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.verticalWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.selected_label = QtWidgets.QLabel(self.verticalWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.selected_label.setFont(font)
        self.selected_label.setObjectName("selected_label")
        self.horizontalLayout_5.addWidget(self.selected_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.verticalWidget_3)
        self.annotation_scene = UAnnotationGraphicsView(annotataion_page)
        self.annotation_scene.setObjectName("annotation_scene")
        self.horizontalLayout_2.addWidget(self.annotation_scene)
        self.verticalWidget_4 = QtWidgets.QWidget(annotataion_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_4.sizePolicy().hasHeightForWidth())
        self.verticalWidget_4.setSizePolicy(sizePolicy)
        self.verticalWidget_4.setMinimumSize(QtCore.QSize(250, 0))
        self.verticalWidget_4.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalWidget_4.setStyleSheet("")
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_13.setMinimumSize(QtCore.QSize(175, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_count_images = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_count_images.setFont(font)
        self.label_count_images.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_count_images.setObjectName("label_count_images")
        self.verticalLayout_8.addWidget(self.label_count_images)
        self.label_count_annotated = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_count_annotated.setFont(font)
        self.label_count_annotated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_count_annotated.setObjectName("label_count_annotated")
        self.verticalLayout_8.addWidget(self.label_count_annotated)
        self.label_count_not_annotated = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_count_not_annotated.setFont(font)
        self.label_count_not_annotated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_count_not_annotated.setObjectName("label_count_not_annotated")
        self.verticalLayout_8.addWidget(self.label_count_not_annotated)
        self.label_count_dropped = QtWidgets.QLabel(self.verticalWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_count_dropped.setFont(font)
        self.label_count_dropped.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_count_dropped.setObjectName("label_count_dropped")
        self.verticalLayout_8.addWidget(self.label_count_dropped)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.list_widget_annotated_on_scene = UListAnnotationWidget(self.verticalWidget_4)
        self.list_widget_annotated_on_scene.setMinimumSize(QtCore.QSize(0, 0))
        self.list_widget_annotated_on_scene.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_widget_annotated_on_scene.setUniformItemSizes(False)
        self.list_widget_annotated_on_scene.setObjectName("list_widget_annotated_on_scene")
        self.verticalLayout_2.addWidget(self.list_widget_annotated_on_scene)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.button_create_dataset = QtWidgets.QPushButton(self.verticalWidget_4)
        self.button_create_dataset.setStyleSheet("QWidget > QPushButton {\n"
"    background-color: rgb(88, 239, 255);\n"
"}\n"
"\n"
"QWidget > QPushButton:hover {\n"
"    background-color: white;\n"
"}")
        self.button_create_dataset.setObjectName("button_create_dataset")
        self.verticalLayout_2.addWidget(self.button_create_dataset)
        self.horizontalLayout_2.addWidget(self.verticalWidget_4)
        self.display_layout.addLayout(self.horizontalLayout_2)
        self.thumbnail_carousel = UThumbnailCarousel(annotataion_page)
        self.thumbnail_carousel.setMinimumSize(QtCore.QSize(0, 200))
        self.thumbnail_carousel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.thumbnail_carousel.setObjectName("thumbnail_carousel")
        self.display_layout.addWidget(self.thumbnail_carousel)
        self.toggle_round_images = QtWidgets.QPushButton(annotataion_page)
        self.toggle_round_images.setEnabled(True)
        self.toggle_round_images.setMouseTracking(True)
        self.toggle_round_images.setAutoFillBackground(False)
        self.toggle_round_images.setStyleSheet("margin-top: 5px;")
        self.toggle_round_images.setAutoRepeat(False)
        self.toggle_round_images.setDefault(True)
        self.toggle_round_images.setObjectName("toggle_round_images")
        self.display_layout.addWidget(self.toggle_round_images)
        self.page_main_layout.addLayout(self.display_layout)

        self.retranslateUi(annotataion_page)
        QtCore.QMetaObject.connectSlotsByName(annotataion_page)

    def retranslateUi(self, annotataion_page):
        _translate = QtCore.QCoreApplication.translate
        annotataion_page.setWindowTitle(_translate("annotataion_page", "Форма для аннотации"))
        self.button_to_datasets_settings.setText(_translate("annotataion_page", "Окно организации датасета"))
        self.button_to_annotation_scene.setText(_translate("annotataion_page", "Окно разметки"))
        self.button_to_statistics.setText(_translate("annotataion_page", "Окно статистики"))
        self.button_clear_dataset.setText(_translate("annotataion_page", "Закрыть проект "))
        self.load_images_button.setText(_translate("annotataion_page", "Загрузить картинки"))
        self.auto_annotate_checkbox.setText(_translate("annotataion_page", "Авторазметка"))
        self.label_6.setText(_translate("annotataion_page", "Режимы разметки"))
        self.select_dragmode_button.setText(_translate("annotataion_page", "1: Перемещение"))
        self.select_annotatemode_button.setText(_translate("annotataion_page", "2: Разметка"))
        self.label_12.setText(_translate("annotataion_page", "Текущий:"))
        self.selected_label.setText(_translate("annotataion_page", "1"))
        self.label_13.setText(_translate("annotataion_page", "Статистика"))
        self.label_14.setText(_translate("annotataion_page", "Разметки на сцене"))
        self.label_15.setText(_translate("annotataion_page", "Загружено:"))
        self.label_16.setText(_translate("annotataion_page", "Размечено:"))
        self.label_17.setText(_translate("annotataion_page", "Не размечено:"))
        self.label_18.setText(_translate("annotataion_page", "Выброшено:"))
        self.label_count_images.setText(_translate("annotataion_page", "0"))
        self.label_count_annotated.setText(_translate("annotataion_page", "0"))
        self.label_count_not_annotated.setText(_translate("annotataion_page", "0"))
        self.label_count_dropped.setText(_translate("annotataion_page", "0"))
        self.button_create_dataset.setText(_translate("annotataion_page", "Добавить в проект"))
        self.toggle_round_images.setText(_translate("annotataion_page", "Скрыть карусель"))
from annotation.annotable import UAnnotationGraphicsView, UClassSelectorList
from annotation.carousel import UThumbnailCarousel
from custom_widgets import UListAnnotationWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    annotataion_page = QtWidgets.QWidget()
    ui = Ui_annotataion_page()
    ui.setupUi(annotataion_page)
    annotataion_page.show()
    sys.exit(app.exec_())
