# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classes_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classes_page_design(object):
    def setupUi(self, classes_page_design):
        classes_page_design.setObjectName("classes_page_design")
        classes_page_design.resize(1388, 805)
        classes_page_design.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.page_main_layout = QtWidgets.QVBoxLayout(classes_page_design)
        self.page_main_layout.setObjectName("page_main_layout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_to_datasets_settings = QtWidgets.QPushButton(classes_page_design)
        self.button_to_datasets_settings.setMouseTracking(True)
        self.button_to_datasets_settings.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid #7a7b7d;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_datasets_settings.setObjectName("button_to_datasets_settings")
        self.horizontalLayout_7.addWidget(self.button_to_datasets_settings)
        self.button_to_annotation_scene = QtWidgets.QPushButton(classes_page_design)
        self.button_to_annotation_scene.setMouseTracking(True)
        self.button_to_annotation_scene.setTabletTracking(False)
        self.button_to_annotation_scene.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_annotation_scene.setObjectName("button_to_annotation_scene")
        self.horizontalLayout_7.addWidget(self.button_to_annotation_scene)
        self.button_to_statistics = QtWidgets.QPushButton(classes_page_design)
        self.button_to_statistics.setMouseTracking(True)
        self.button_to_statistics.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_to_statistics.setObjectName("button_to_statistics")
        self.horizontalLayout_7.addWidget(self.button_to_statistics)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem)
        self.button_clear_dataset = QtWidgets.QPushButton(classes_page_design)
        self.button_clear_dataset.setMouseTracking(True)
        self.button_clear_dataset.setStyleSheet("QPushButton {\n"
"padding: 5px 20px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 1px solid #0048ff;\n"
"}")
        self.button_clear_dataset.setObjectName("button_clear_dataset")
        self.horizontalLayout_7.addWidget(self.button_clear_dataset)
        self.page_main_layout.addLayout(self.horizontalLayout_7)
        self.dataset_display = QtWidgets.QWidget(classes_page_design)
        self.dataset_display.setObjectName("dataset_display")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataset_display)
        self.verticalLayout.setContentsMargins(1, -1, 1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chart_classes = UWidgetChart(self.dataset_display)
        self.chart_classes.setMinimumSize(QtCore.QSize(0, 600))
        self.chart_classes.setObjectName("chart_classes")
        self.verticalLayout.addWidget(self.chart_classes)
        self.page_main_layout.addWidget(self.dataset_display)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.page_main_layout.addItem(spacerItem1)

        self.retranslateUi(classes_page_design)
        QtCore.QMetaObject.connectSlotsByName(classes_page_design)

    def retranslateUi(self, classes_page_design):
        _translate = QtCore.QCoreApplication.translate
        classes_page_design.setWindowTitle(_translate("classes_page_design", "Форма для аннотации"))
        self.button_to_datasets_settings.setText(_translate("classes_page_design", "Окно организации датасета"))
        self.button_to_annotation_scene.setText(_translate("classes_page_design", "Окно разметки"))
        self.button_to_statistics.setText(_translate("classes_page_design", "Окно статистики"))
        self.button_clear_dataset.setText(_translate("classes_page_design", "Закрыть проект"))
from class_chart import UWidgetChart


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classes_page_design = QtWidgets.QWidget()
    ui = Ui_classes_page_design()
    ui.setupUi(classes_page_design)
    classes_page_design.show()
    sys.exit(app.exec_())
