# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classes_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classes_page_design(object):
    def setupUi(self, classes_page_design):
        classes_page_design.setObjectName("classes_page_design")
        classes_page_design.resize(1388, 805)
        classes_page_design.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.page_main_layout = QtWidgets.QVBoxLayout(classes_page_design)
        self.page_main_layout.setObjectName("page_main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chart_classes = UWidgetChart(classes_page_design)
        self.chart_classes.setMinimumSize(QtCore.QSize(0, 600))
        self.chart_classes.setObjectName("chart_classes")
        self.horizontalLayout.addWidget(self.chart_classes)
        self.verticalWidget = QtWidgets.QWidget(classes_page_design)
        self.verticalWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_show_all = QtWidgets.QPushButton(self.verticalWidget)
        self.button_show_all.setObjectName("button_show_all")
        self.verticalLayout.addWidget(self.button_show_all)
        self.list_stat_item = QtWidgets.QListWidget(self.verticalWidget)
        self.list_stat_item.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_stat_item.setObjectName("list_stat_item")
        self.verticalLayout.addWidget(self.list_stat_item)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.page_main_layout.addLayout(self.horizontalLayout)

        self.retranslateUi(classes_page_design)
        QtCore.QMetaObject.connectSlotsByName(classes_page_design)

    def retranslateUi(self, classes_page_design):
        _translate = QtCore.QCoreApplication.translate
        classes_page_design.setWindowTitle(_translate("classes_page_design", "Форма для аннотации"))
        self.button_show_all.setText(_translate("classes_page_design", "Вывести все"))
from class_chart import UWidgetChart


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classes_page_design = QtWidgets.QWidget()
    ui = Ui_classes_page_design()
    ui.setupUi(classes_page_design)
    classes_page_design.show()
    sys.exit(app.exec_())
