# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classes_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from annotation.annotation_scene import UClassSelectorList, UClassSelectorItem


class Ui_classes_page_design(object):
    def setupUi(self, classes_page_design):
        classes_page_design.setObjectName("classes_page_design")
        classes_page_design.resize(1388, 805)
        classes_page_design.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.page_main_layout = QtWidgets.QVBoxLayout(classes_page_design)
        self.page_main_layout.setObjectName("page_main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(classes_page_design)
        self.verticalWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.list_classes = UClassSelectorList(self.groupBox_2)
        self.list_classes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_classes.setObjectName("list_classes")
        self.verticalLayout_4.addWidget(self.list_classes)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineedit_enter_class = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineedit_enter_class.setFont(font)
        self.lineedit_enter_class.setText("")
        self.lineedit_enter_class.setObjectName("lineedit_enter_class")
        self.verticalLayout_3.addWidget(self.lineedit_enter_class)
        self.button_add_class = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_add_class.setFont(font)
        self.button_add_class.setObjectName("button_add_class")
        self.verticalLayout_3.addWidget(self.button_add_class)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.combo_type = EnumComboBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_type.setFont(font)
        self.combo_type.setObjectName("combo_type")
        self.verticalLayout_5.addWidget(self.combo_type)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.chart_classes = UWidgetChart(classes_page_design)
        self.chart_classes.setMinimumSize(QtCore.QSize(0, 600))
        self.chart_classes.setObjectName("chart_classes")
        self.horizontalLayout.addWidget(self.chart_classes)
        self.verticalWidget1 = QtWidgets.QWidget(classes_page_design)
        self.verticalWidget1.setMaximumSize(QtCore.QSize(250, 16777215))
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_show_all = QtWidgets.QPushButton(self.verticalWidget1)
        self.button_show_all.setObjectName("button_show_all")
        self.verticalLayout.addWidget(self.button_show_all)
        self.list_stat_item = QtWidgets.QListWidget(self.verticalWidget1)
        self.list_stat_item.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.list_stat_item.setObjectName("list_stat_item")
        self.verticalLayout.addWidget(self.list_stat_item)
        self.horizontalLayout.addWidget(self.verticalWidget1)
        self.page_main_layout.addLayout(self.horizontalLayout)

        self.retranslateUi(classes_page_design)
        QtCore.QMetaObject.connectSlotsByName(classes_page_design)

    def retranslateUi(self, classes_page_design):
        _translate = QtCore.QCoreApplication.translate
        classes_page_design.setWindowTitle(_translate("classes_page_design", "Форма для аннотации"))
        self.groupBox_2.setTitle(_translate("classes_page_design", "Список классов"))
        self.groupBox.setTitle(_translate("classes_page_design", "Добавление класса"))
        self.lineedit_enter_class.setPlaceholderText(_translate("classes_page_design", "Введите название нового класса"))
        self.button_add_class.setText(_translate("classes_page_design", "Добавить класс"))
        self.groupBox_3.setTitle(_translate("classes_page_design", "Отображение статистики"))
        self.button_show_all.setText(_translate("classes_page_design", "Вывести все"))

from dataset.dataset_widgets import EnumComboBox
from stats.class_chart import UWidgetChart


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    classes_page_design = QtWidgets.QWidget()
    ui = Ui_classes_page_design()
    ui.setupUi(classes_page_design)
    classes_page_design.show()
    sys.exit(app.exec_())
