# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_export.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_export(object):
    def setupUi(self, dialog_export):
        dialog_export.setObjectName("dialog_export")
        dialog_export.resize(441, 641)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_export)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_choose_path = QtWidgets.QPushButton(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_choose_path.setFont(font)
        self.button_choose_path.setObjectName("button_choose_path")
        self.horizontalLayout.addWidget(self.button_choose_path)
        self.label_path = QtWidgets.QLabel(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_path.setFont(font)
        self.label_path.setStyleSheet("border: 1px solid gray;\n"
"background-color: white;")
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.horizontalLayout.addWidget(self.label_path)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_enable_datasets = QtWidgets.QPushButton(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_enable_datasets.setFont(font)
        self.button_enable_datasets.setObjectName("button_enable_datasets")
        self.horizontalLayout_2.addWidget(self.button_enable_datasets)
        self.button_enable_classes = QtWidgets.QPushButton(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_enable_classes.setFont(font)
        self.button_enable_classes.setObjectName("button_enable_classes")
        self.horizontalLayout_2.addWidget(self.button_enable_classes)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stack_export = QtWidgets.QStackedWidget(dialog_export)
        self.stack_export.setMinimumSize(QtCore.QSize(0, 400))
        self.stack_export.setObjectName("stack_export")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list_choose_datasets = QtWidgets.QListWidget(self.page_2)
        self.list_choose_datasets.setStyleSheet("QListWidget {\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px 8px;\n"
"    margin: 2px 4px;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #d0e4f7;  /* мягкий голубой */\n"
"    color: #333333;\n"
"    border: 1px solid #6699cc;\n"
"}")
        self.list_choose_datasets.setObjectName("list_choose_datasets")
        self.verticalLayout_2.addWidget(self.list_choose_datasets)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_choose_all = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_choose_all.setFont(font)
        self.button_choose_all.setObjectName("button_choose_all")
        self.horizontalLayout_3.addWidget(self.button_choose_all)
        self.button_cancel_all = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_cancel_all.setFont(font)
        self.button_cancel_all.setObjectName("button_cancel_all")
        self.horizontalLayout_3.addWidget(self.button_cancel_all)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stack_export.addWidget(self.page_2)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_21)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_choose_classes = QtWidgets.QListWidget(self.page_21)
        self.list_choose_classes.setStyleSheet("QListWidget {\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px 8px;\n"
"    margin: 2px 4px;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #d0e4f7;  /* мягкий голубой */\n"
"    color: #333333;\n"
"    border: 1px solid #6699cc;\n"
"}")
        self.list_choose_classes.setObjectName("list_choose_classes")
        self.verticalLayout_3.addWidget(self.list_choose_classes)
        self.stack_export.addWidget(self.page_21)
        self.verticalLayout.addWidget(self.stack_export)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.button_start_export = QtWidgets.QPushButton(dialog_export)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_start_export.setFont(font)
        self.button_start_export.setStyleSheet("QDialog > QPushButton {\n"
"    background-color: rgb(88, 239, 255);\n"
"}\n"
"\n"
"QDialog > QPushButton:hover {\n"
"    background-color: white;\n"
"}")
        self.button_start_export.setObjectName("button_start_export")
        self.verticalLayout.addWidget(self.button_start_export)

        self.retranslateUi(dialog_export)
        self.stack_export.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog_export)

    def retranslateUi(self, dialog_export):
        _translate = QtCore.QCoreApplication.translate
        dialog_export.setWindowTitle(_translate("dialog_export", "Dialog"))
        self.label.setText(_translate("dialog_export", "Выберите путь для экспорта"))
        self.button_choose_path.setText(_translate("dialog_export", "Выбрать"))
        self.label_2.setText(_translate("dialog_export", "Настройка параметров экспорта"))
        self.button_enable_datasets.setText(_translate("dialog_export", "Датасеты"))
        self.button_enable_classes.setText(_translate("dialog_export", "Классы"))
        self.button_choose_all.setText(_translate("dialog_export", "Выделить все"))
        self.button_cancel_all.setText(_translate("dialog_export", "Снять все"))
        self.button_start_export.setText(_translate("dialog_export", "Экспорт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_export = QtWidgets.QDialog()
    ui = Ui_dialog_export()
    ui.setupUi(dialog_export)
    dialog_export.show()
    sys.exit(app.exec_())
