# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_add_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_add_class(object):
    def setupUi(self, dialog_add_class):
        dialog_add_class.setObjectName("dialog_add_class")
        dialog_add_class.resize(253, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_add_class.sizePolicy().hasHeightForWidth())
        dialog_add_class.setSizePolicy(sizePolicy)
        dialog_add_class.setStyleSheet("QDialog {\n"
"    background-color: rgba(50, 50, 50, 200);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3c3f41;\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    padding: 2px 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00cc66;\n"
"    border: 2px solid #00ff88;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_add_class)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(dialog_add_class)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineedit_class_name = QtWidgets.QLineEdit(dialog_add_class)
        self.lineedit_class_name.setObjectName("lineedit_class_name")
        self.verticalLayout.addWidget(self.lineedit_class_name)
        self.label_3 = QtWidgets.QLabel(dialog_add_class)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineedit_supercategory = QtWidgets.QLineEdit(dialog_add_class)
        self.lineedit_supercategory.setObjectName("lineedit_supercategory")
        self.verticalLayout.addWidget(self.lineedit_supercategory)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_choose_color = QtWidgets.QPushButton(dialog_add_class)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_choose_color.sizePolicy().hasHeightForWidth())
        self.button_choose_color.setSizePolicy(sizePolicy)
        self.button_choose_color.setStyleSheet("QPushButton {\n"
"    background-color: #00cc66;\n"
"    border: 2px solid #00ff88;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}")
        self.button_choose_color.setObjectName("button_choose_color")
        self.horizontalLayout.addWidget(self.button_choose_color)
        self.label_class_color = QtWidgets.QLabel(dialog_add_class)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_class_color.sizePolicy().hasHeightForWidth())
        self.label_class_color.setSizePolicy(sizePolicy)
        self.label_class_color.setMinimumSize(QtCore.QSize(40, 0))
        self.label_class_color.setStyleSheet("    border: 2px solid #00ff88;\n"
"    border-radius: 6px;\n"
"    font-family: Arial\n"
"")
        self.label_class_color.setText("")
        self.label_class_color.setObjectName("label_class_color")
        self.horizontalLayout.addWidget(self.label_class_color)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_add_class = QtWidgets.QPushButton(dialog_add_class)
        self.button_add_class.setStyleSheet("font-size: 16px;")
        self.button_add_class.setObjectName("button_add_class")
        self.verticalLayout.addWidget(self.button_add_class)

        self.retranslateUi(dialog_add_class)
        QtCore.QMetaObject.connectSlotsByName(dialog_add_class)

    def retranslateUi(self, dialog_add_class):
        _translate = QtCore.QCoreApplication.translate
        dialog_add_class.setWindowTitle(_translate("dialog_add_class", "Добавление нового класса"))
        self.label_2.setText(_translate("dialog_add_class", "Название класса"))
        self.label_3.setText(_translate("dialog_add_class", "Категория"))
        self.button_choose_color.setText(_translate("dialog_add_class", "Выбрать цвет"))
        self.button_add_class.setText(_translate("dialog_add_class", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_add_class = QtWidgets.QDialog()
    ui = Ui_dialog_add_class()
    ui.setupUi(dialog_add_class)
    dialog_add_class.show()
    sys.exit(app.exec_())
