# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_model(object):
    def setupUi(self, page_model):
        page_model.setObjectName("page_model")
        page_model.resize(1388, 867)
        page_model.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.page_main_layout = QtWidgets.QVBoxLayout(page_model)
        self.page_main_layout.setSpacing(5)
        self.page_main_layout.setObjectName("page_main_layout")
        self.dataset_display = QtWidgets.QWidget(page_model)
        self.dataset_display.setObjectName("dataset_display")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dataset_display)
        self.horizontalLayout.setContentsMargins(1, -1, 1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_status = QtWidgets.QLabel(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("QLabel {\n"
"color: red;\n"
"}")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.button_load_local = QtWidgets.QPushButton(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_load_local.setFont(font)
        self.button_load_local.setObjectName("button_load_local")
        self.verticalLayout_2.addWidget(self.button_load_local)
        self.label_2 = QtWidgets.QLabel(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.line_ip_address = QtWidgets.QLineEdit(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_ip_address.setFont(font)
        self.line_ip_address.setObjectName("line_ip_address")
        self.verticalLayout_2.addWidget(self.line_ip_address)
        self.label_3 = QtWidgets.QLabel(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_port = QtWidgets.QLineEdit(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_port.setFont(font)
        self.line_port.setObjectName("line_port")
        self.verticalLayout_2.addWidget(self.line_port)
        self.button_connect_remote = QtWidgets.QPushButton(self.dataset_display)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_connect_remote.setFont(font)
        self.button_connect_remote.setObjectName("button_connect_remote")
        self.verticalLayout_2.addWidget(self.button_connect_remote)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalWidget = QtWidgets.QWidget(self.dataset_display)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 4)
        self.page_main_layout.addWidget(self.dataset_display)

        self.retranslateUi(page_model)
        QtCore.QMetaObject.connectSlotsByName(page_model)

    def retranslateUi(self, page_model):
        _translate = QtCore.QCoreApplication.translate
        page_model.setWindowTitle(_translate("page_model", "Форма для аннотации"))
        self.label.setText(_translate("page_model", "Подключение модели"))
        self.label_status.setText(_translate("page_model", "Не загружена!"))
        self.button_load_local.setText(_translate("page_model", "Загрузить локально"))
        self.label_2.setText(_translate("page_model", "IP адрес"))
        self.label_3.setText(_translate("page_model", "Порт"))
        self.button_connect_remote.setText(_translate("page_model", "Подключить удаленно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_model = QtWidgets.QWidget()
    ui = Ui_page_model()
    ui.setupUi(page_model)
    page_model.show()
    sys.exit(app.exec_())
