# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_save_load.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_load_dataset(object):
    def setupUi(self, page_load_dataset):
        page_load_dataset.setObjectName("page_load_dataset")
        page_load_dataset.resize(1155, 815)
        self.page_main_layout = QtWidgets.QVBoxLayout(page_load_dataset)
        self.page_main_layout.setObjectName("page_main_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.button_load_train_project = QtWidgets.QPushButton(page_load_dataset)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_load_train_project.setFont(font)
        self.button_load_train_project.setObjectName("button_load_train_project")
        self.verticalLayout_6.addWidget(self.button_load_train_project)
        self.button_create_train_project = QtWidgets.QPushButton(page_load_dataset)
        self.button_create_train_project.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_create_train_project.setFont(font)
        self.button_create_train_project.setObjectName("button_create_train_project")
        self.verticalLayout_6.addWidget(self.button_create_train_project)
        self.button_coco_test = QtWidgets.QPushButton(page_load_dataset)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_coco_test.setFont(font)
        self.button_coco_test.setObjectName("button_coco_test")
        self.verticalLayout_6.addWidget(self.button_coco_test)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.page_main_layout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(page_load_dataset)
        QtCore.QMetaObject.connectSlotsByName(page_load_dataset)

    def retranslateUi(self, page_load_dataset):
        _translate = QtCore.QCoreApplication.translate
        page_load_dataset.setWindowTitle(_translate("page_load_dataset", "Главная страница"))
        self.button_load_train_project.setText(_translate("page_load_dataset", "Загрузить тренировочный проект"))
        self.button_create_train_project.setText(_translate("page_load_dataset", "Создать тренировочный проект"))
        self.button_coco_test.setText(_translate("page_load_dataset", "Загрузить COCO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_load_dataset = QtWidgets.QWidget()
    ui = Ui_page_load_dataset()
    ui.setupUi(page_load_dataset)
    page_load_dataset.show()
    sys.exit(app.exec_())
