# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sam2_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(269, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        Dialog.setWindowOpacity(0.75)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: rgba(50, 50, 50, 200);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    padding: 2px 10px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    background-color: #222222;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #00cc66;\n"
"    border: 2px solid #00ff88;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #888;\n"
"    background-color: #444;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color: #222;\n"
"    border: 2px solid #666;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    font-size: 12px;\n"
"    padding: 2px 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #00cc66;\n"
"    border: 2px solid #00ff88;\n"
"    color: white;\n"
"    font-family: Arial;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #00cc66;\n"
"    border: none;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -4px 0;  \n"
"    border-radius: 7px; \n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #218838;  \n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #1e7e34;   \n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 2px solid #00ff88;\n"
"    border-radius: 4px;\n"
"    background-color: #222222;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    text-align: center;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"        background-color: #222222;\n"
"        color: white;\n"
"        border: 1px solid #00ff88;\n"
"        selection-background-color: #222222;\n"
"        selection-color: #00ff88;\n"
"        padding: 4px;\n"
"        outline: 0;\n"
"        show-decoration-selected: 1;\n"
"    }\n"
"\n"
"    QComboBox QAbstractItemView::item {\n"
"        padding: 6px;\n"
"        margin: 2px;\n"
"        border-radius: 4px;\n"
"        background-color: #222222;\n"
"        color: white;\n"
"    }")
        Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_points = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.radio_points.setFont(font)
        self.radio_points.setChecked(True)
        self.radio_points.setObjectName("radio_points")
        self.verticalLayout.addWidget(self.radio_points)
        self.radio_box = QtWidgets.QRadioButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.radio_box.setFont(font)
        self.radio_box.setCheckable(True)
        self.radio_box.setChecked(False)
        self.radio_box.setObjectName("radio_box")
        self.verticalLayout.addWidget(self.radio_box)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_result = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result.sizePolicy().hasHeightForWidth())
        self.label_result.setSizePolicy(sizePolicy)
        self.label_result.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_result.setObjectName("label_result")
        self.horizontalLayout_4.addWidget(self.label_result)
        self.combo_result = QtWidgets.QComboBox(Dialog)
        self.combo_result.setObjectName("combo_result")
        self.combo_result.addItem("")
        self.combo_result.addItem("")
        self.horizontalLayout_4.addWidget(self.combo_result)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_polygon = QtWidgets.QLabel(Dialog)
        self.label_polygon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_polygon.sizePolicy().hasHeightForWidth())
        self.label_polygon.setSizePolicy(sizePolicy)
        self.label_polygon.setScaledContents(False)
        self.label_polygon.setObjectName("label_polygon")
        self.horizontalLayout_2.addWidget(self.label_polygon)
        self.label_count = QtWidgets.QLabel(Dialog)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout_2.addWidget(self.label_count)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.slider_approximation = QtWidgets.QSlider(Dialog)
        self.slider_approximation.setOrientation(QtCore.Qt.Horizontal)
        self.slider_approximation.setObjectName("slider_approximation")
        self.verticalLayout.addWidget(self.slider_approximation)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ap_text = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ap_text.sizePolicy().hasHeightForWidth())
        self.label_ap_text.setSizePolicy(sizePolicy)
        self.label_ap_text.setObjectName("label_ap_text")
        self.horizontalLayout_3.addWidget(self.label_ap_text)
        self.label_approximation = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_approximation.sizePolicy().hasHeightForWidth())
        self.label_approximation.setSizePolicy(sizePolicy)
        self.label_approximation.setObjectName("label_approximation")
        self.horizontalLayout_3.addWidget(self.label_approximation)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_make_polygons = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_make_polygons.sizePolicy().hasHeightForWidth())
        self.button_make_polygons.setSizePolicy(sizePolicy)
        self.button_make_polygons.setObjectName("button_make_polygons")
        self.horizontalLayout.addWidget(self.button_make_polygons)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radio_points.setText(_translate("Dialog", "Использовать точки"))
        self.radio_box.setText(_translate("Dialog", "Использовать бокс"))
        self.label_result.setText(_translate("Dialog", "Результат"))
        self.combo_result.setItemText(0, _translate("Dialog", "Маска"))
        self.combo_result.setItemText(1, _translate("Dialog", "Рамка"))
        self.label_polygon.setText(_translate("Dialog", "Количество полигонов:"))
        self.label_count.setText(_translate("Dialog", "0"))
        self.label_ap_text.setText(_translate("Dialog", "Аппроксимация:"))
        self.label_approximation.setText(_translate("Dialog", "1"))
        self.button_make_polygons.setText(_translate("Dialog", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
