# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainApp(object):
    def setupUi(self, TrainApp):
        TrainApp.setObjectName("TrainApp")
        TrainApp.resize(1153, 812)
        TrainApp.setAutoFillBackground(False)
        TrainApp.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(TrainApp)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: lightgray;\n"
"    color: black;            \n"
"    border: 1px solid lightgray; \n"
"    padding: 5px 0px;    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border: 1px solid blue;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: solid lightblue;\n"
"    border: 1px solid black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_page_loader = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_page_loader.setObjectName("stacked_page_loader")
        self.verticalLayout_2.addWidget(self.stacked_page_loader)
        TrainApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TrainApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 21))
        self.menubar.setObjectName("menubar")
        TrainApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TrainApp)
        self.statusbar.setObjectName("statusbar")
        TrainApp.setStatusBar(self.statusbar)

        self.retranslateUi(TrainApp)
        QtCore.QMetaObject.connectSlotsByName(TrainApp)

    def retranslateUi(self, TrainApp):
        _translate = QtCore.QCoreApplication.translate
        TrainApp.setWindowTitle(_translate("TrainApp", "Train App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainApp = QtWidgets.QMainWindow()
    ui = Ui_TrainApp()
    ui.setupUi(TrainApp)
    TrainApp.show()
    sys.exit(app.exec_())
