# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_create_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_create_project(object):
    def setupUi(self, window_create_project):
        window_create_project.setObjectName("window_create_project")
        window_create_project.resize(480, 420)
        window_create_project.setMinimumSize(QtCore.QSize(480, 420))
        window_create_project.setMaximumSize(QtCore.QSize(480, 420))
        self.verticalLayout = QtWidgets.QVBoxLayout(window_create_project)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineedit_project_name = QtWidgets.QLineEdit(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineedit_project_name.setFont(font)
        self.lineedit_project_name.setObjectName("lineedit_project_name")
        self.verticalLayout.addWidget(self.lineedit_project_name)
        self.label_2 = QtWidgets.QLabel(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.button_choose_project_path = QtWidgets.QPushButton(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_choose_project_path.setFont(font)
        self.button_choose_project_path.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    padding: 5px 15px;\n"
"}")
        self.button_choose_project_path.setObjectName("button_choose_project_path")
        self.verticalLayout.addWidget(self.button_choose_project_path)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.button_load_classes = QtWidgets.QPushButton(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_load_classes.setFont(font)
        self.button_load_classes.setObjectName("button_load_classes")
        self.horizontalLayout.addWidget(self.button_load_classes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineedit_add_class = QtWidgets.QLineEdit(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineedit_add_class.setFont(font)
        self.lineedit_add_class.setStyleSheet("QLineEdit {\n"
"    padding: 5px 10px;\n"
"}")
        self.lineedit_add_class.setObjectName("lineedit_add_class")
        self.horizontalLayout_2.addWidget(self.lineedit_add_class)
        self.button_add_class = QtWidgets.QPushButton(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_add_class.setFont(font)
        self.button_add_class.setStyleSheet("QPushButton {\n"
"    padding: 5px 10px;\n"
"}")
        self.button_add_class.setObjectName("button_add_class")
        self.horizontalLayout_2.addWidget(self.button_add_class)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.browser_added_classes = QtWidgets.QTextBrowser(window_create_project)
        self.browser_added_classes.setObjectName("browser_added_classes")
        self.verticalLayout.addWidget(self.browser_added_classes)
        self.button_create_project = QtWidgets.QPushButton(window_create_project)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_create_project.setFont(font)
        self.button_create_project.setObjectName("button_create_project")
        self.verticalLayout.addWidget(self.button_create_project)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(window_create_project)
        QtCore.QMetaObject.connectSlotsByName(window_create_project)

    def retranslateUi(self, window_create_project):
        _translate = QtCore.QCoreApplication.translate
        window_create_project.setWindowTitle(_translate("window_create_project", "Dialog"))
        self.label.setText(_translate("window_create_project", "Создание проекта"))
        self.label_3.setText(_translate("window_create_project", "Название проекта:"))
        self.label_2.setText(_translate("window_create_project", "Путь к проекту:"))
        self.button_choose_project_path.setText(_translate("window_create_project", "Нажмите для выбора пути к проекту"))
        self.label_4.setText(_translate("window_create_project", "Если есть список классов:"))
        self.button_load_classes.setText(_translate("window_create_project", "Загрузить"))
        self.label_5.setText(_translate("window_create_project", "Добавить класс:"))
        self.button_add_class.setText(_translate("window_create_project", "Добавить"))
        self.button_create_project.setText(_translate("window_create_project", "Создать проект"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_create_project = QtWidgets.QDialog()
    ui = Ui_window_create_project()
    ui.setupUi(window_create_project)
    window_create_project.show()
    sys.exit(app.exec_())
