version: "3.8"

services:
  varan-server:
    build: .
    container_name: varan-server
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=6788
    ports:
      - "6788:6788"
    restart: unless-stopped